### ISSUE TITLE
What is the state of the project?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [z3ntu/razer_test#11]
Hey z3ntu,
Thank you for all your effort so far!
Could you maybe add a few lines in the wiki as to where you are with the project and how we could help out? I'm not a drivers/os guy but I could help out with higher level things

**Comment by z3ntu** [comment]
Hi, the code generally works fine on the devices that are supported (a.k.a the ones I own). As you can see there are several pull requests open with more devices which (should) work fine as well.
I mostly want to finish my `better-bringup-v2` branch (for https://github.com/z3ntu/razer_test/projects/1#card-18608926), make libopenrazer (my C++/Qt bindings for the dbus API used in RazerGenie) work a bit better and be able to compile without the header from this repo (if openrazer is targeted) and probably the first 3 items in "To do" at https://github.com/z3ntu/razer_test/projects/1#column-3261743 .

What you could do to help me is to compile the `better-bringup-v2` branch (follow normal meson procedure: `meson builddir` and `ninja -C builddir`) and test the razer_test_bringup_util (binary can be found in the builddir) and report back what you notice (I don't give you more instructions on purpose because it should be self explainable :wink: )

And of course, thanks for your interest in the project :)

**Comment by mubartok** [comment]
Hey there, I dont't know if you're still working on this, but I'd love to be able to set up/use my windows profiles on my MBP :)

I'm using a Mamba Wireless (the latest version released in 2018), and Synapse 2.0 just doesn't recognize my device at all. So I always have this breathing rainbow effect and I can't set anything up... Hopefully you already plan to make it compatible with my device, if not would you recommend any other solution? I'd really like to either disable the lighting or be able to change the breathing effect to a static color.

I would've enjoyed to give you a hand on this but I'm not a C++ specialist at all... But that's awesome that you eventually decided to port OpenRazer to macOS!

**Comment by turbos-and-tacos** [comment]
I got everything up everything up and running. No in scope issues. (unsupported devices didn't work, but that is to be expected) My test device was a DeathAdder Chroma.

Anything else I can help with?
